// Configuration for the six visually distinct celestial service planets including 3D orbital motion parameters
export const PLANET_DATA = [
  {
    id: "websites",
    name: "Websites",
    service: "Websites & Brand Experiences",
    orbitIndex: 0, // Radius 2.5 (Inner orbit - fastest)
    size: 0.28,
    initialAngle: 0.75, // Radians
    orbitSpeed: 0.12, // Radians per second
    selfRotationSpeed: 0.15,
    baseColor: "#0284c7",
    secondaryColor: "#15803d",
    accentColor: "#78350f",
    surfaceType: "terrestrial",
    hasClouds: true,
    cloudColor: "#ffffff",
    hasAtmosphere: true,
    atmosphereColor: "#38bdf8",
    roughness: 0.45,
    metalness: 0.05,
  },
  {
    id: "web-apps",
    name: "Web Applications",
    service: "Web Applications & SaaS Platforms",
    orbitIndex: 1, // Radius 3.7 (Inner-middle orbit)
    size: 0.36,
    initialAngle: 3.15,
    orbitSpeed: 0.08,
    selfRotationSpeed: 0.12,
    baseColor: "#262626",
    secondaryColor: "#78350f",
    accentColor: "#d97706",
    surfaceType: "rocky",
    hasClouds: false,
    hasAtmosphere: false,
    roughness: 0.85,
    metalness: 0.1,
  },
  {
    id: "full-stack",
    name: "Full-Stack Development",
    service: "Full-Stack Software Architecture",
    orbitIndex: 2, // Radius 5.0 (Middle Gold orbit)
    size: 0.44,
    initialAngle: 1.85,
    orbitSpeed: 0.055,
    selfRotationSpeed: 0.10,
    baseColor: "#1e3a8a",
    secondaryColor: "#0284c7",
    accentColor: "#06b6d4",
    surfaceType: "gas",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#60a5fa",
    roughness: 0.25,
    metalness: 0.05,
  },
  {
    id: "mobile-desktop",
    name: "Mobile & Desktop Apps",
    service: "Native & Cross-Platform Applications",
    orbitIndex: 3, // Radius 6.3 (Outer-middle orbit)
    size: 0.34,
    initialAngle: 4.65,
    orbitSpeed: 0.038,
    selfRotationSpeed: 0.08,
    baseColor: "#18181b",
    secondaryColor: "#991b1b",
    accentColor: "#ea580c",
    surfaceType: "volcanic",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#b91c1c",
    roughness: 0.9,
    metalness: 0.2,
    emissiveLava: true,
  },
  {
    id: "erp-systems",
    name: "ERP & Business Systems",
    service: "Enterprise ERP & Operations Systems",
    orbitIndex: 4, // Radius 7.7 (Outer orbit - slowest)
    size: 0.42,
    initialAngle: 3.85,
    orbitSpeed: 0.024,
    selfRotationSpeed: 0.06,
    baseColor: "#334155",
    secondaryColor: "#1e293b",
    accentColor: "#64748b",
    surfaceType: "darkRock",
    hasRings: true,
    ringColor: "#94a3b8",
    hasClouds: false,
    hasAtmosphere: false,
    roughness: 0.85,
    metalness: 0.35,
  },
  {
    id: "custom-software",
    name: "Custom Software",
    service: "Custom Software & API Integrations",
    orbitIndex: 1, // Shared Orbit 2 (Radius 3.7)
    size: 0.31,
    initialAngle: 0.25,
    orbitSpeed: 0.08,
    selfRotationSpeed: 0.14,
    baseColor: "#e0f2fe",
    secondaryColor: "#0284c7",
    accentColor: "#38bdf8",
    surfaceType: "ice",
    hasRings: true,
    ringColor: "#67e8f9",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#7dd3fc",
    roughness: 0.15,
    metalness: 0.4,
  },
];
