// Configuration for the six service planets with realistic art direction & 3D attributes
export const PLANET_DATA = [
  {
    id: "websites",
    name: "Websites",
    service: "Websites & Brand Experiences",
    orbitIndex: 0, // Radius 2.5
    size: 0.28,
    initialAngle: 0.75, // Top-right inner orbit
    baseColor: "#0284c7",
    secondaryColor: "#38bdf8",
    accentColor: "#0f172a",
    surfaceType: "terrestrial",
    hasClouds: true,
    cloudColor: "#ffffff",
    hasAtmosphere: true,
    atmosphereColor: "#38bdf8",
    roughness: 0.4,
    metalness: 0.1,
  },
  {
    id: "web-apps",
    name: "Web Applications",
    service: "Web Applications & SaaS Platforms",
    orbitIndex: 1, // Radius 3.7
    size: 0.36,
    initialAngle: 3.15, // Far left orbit
    baseColor: "#d97706",
    secondaryColor: "#fbbf24",
    accentColor: "#78350f",
    surfaceType: "gas-giant",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#f59e0b",
    roughness: 0.3,
    metalness: 0.05,
  },
  {
    id: "full-stack",
    name: "Full-Stack Development",
    service: "Full-Stack Software Architecture",
    orbitIndex: 2, // Radius 5.0 (Gold orbit)
    size: 0.44,
    initialAngle: 1.85, // Top-center orbit position
    baseColor: "#1d4ed8",
    secondaryColor: "#60a5fa",
    accentColor: "#0f172a",
    surfaceType: "terrestrial",
    hasClouds: true,
    cloudColor: "#e0f2fe",
    hasAtmosphere: true,
    atmosphereColor: "#3b82f6",
    roughness: 0.35,
    metalness: 0.1,
  },
  {
    id: "mobile-desktop",
    name: "Mobile & Desktop Apps",
    service: "Native & Cross-Platform Applications",
    orbitIndex: 3, // Radius 6.3
    size: 0.34,
    initialAngle: 4.65, // Bottom-left orbit position
    baseColor: "#c2410c",
    secondaryColor: "#ea580c",
    accentColor: "#451a03",
    surfaceType: "canyon",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#f97316",
    roughness: 0.75,
    metalness: 0.15,
  },
  {
    id: "erp-systems",
    name: "ERP & Business Systems",
    service: "Enterprise ERP & Operations Systems",
    orbitIndex: 4, // Radius 7.7
    size: 0.42,
    initialAngle: 3.85, // Far bottom-left outer orbit (separated from custom-software)
    baseColor: "#64748b",
    secondaryColor: "#cbd5e1",
    accentColor: "#334155",
    surfaceType: "industrial",
    hasRings: true,
    ringInnerRadius: 0.52,
    ringOuterRadius: 0.85,
    ringColor: "#cbd5e1",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#94a3b8",
    roughness: 0.3,
    metalness: 0.4,
  },
  {
    id: "custom-software",
    name: "Custom Software",
    service: "Custom Software & API Integrations",
    orbitIndex: 1, // Shared Orbit 2 (Radius 3.7)
    size: 0.31,
    initialAngle: 0.25, // Top-right orbit (separated from erp-systems)
    baseColor: "#0891b2",
    secondaryColor: "#a5f3fc",
    accentColor: "#164e63",
    surfaceType: "crystal",
    hasRings: true,
    ringInnerRadius: 0.40,
    ringOuterRadius: 0.62,
    ringColor: "#67e8f9",
    hasClouds: false,
    hasAtmosphere: true,
    atmosphereColor: "#22d3ee",
    roughness: 0.2,
    metalness: 0.3,
  },
];
