// Complete configuration for all 8 photorealistic celestial planets of the Solar System
export const PLANET_DATA = [
  {
    id: "mercury",
    name: "Mercury",
    service: "High-Performance Speed & Core APIs",
    orbitIndex: 0, // Radius 2.2
    size: 0.22,
    initialAngle: 0.8,
    orbitSpeed: 0.16,
    selfRotationSpeed: 0.18,
    texture: "/textures/mercury.jpg",
    roughness: 1.00,
    metalness: 0.02,
    bumpScale: 0.025,
    hasAtmosphere: false,
    atmosphereColor: "#94a3b8",
  },
  {
    id: "venus",
    name: "Venus",
    service: "Custom Software & API Integrations",
    orbitIndex: 1, // Radius 3.0
    size: 0.30,
    initialAngle: 3.5,
    orbitSpeed: 0.11,
    selfRotationSpeed: 0.12,
    texture: "/textures/venus.jpg",
    roughness: 0.60,
    metalness: 0.05,
    bumpScale: 0.015,
    hasAtmosphere: true,
    atmosphereColor: "#fdba74",
  },
  {
    id: "earth",
    name: "Earth",
    service: "Websites & Brand Experiences",
    orbitIndex: 2, // Radius 3.9
    size: 0.34,
    initialAngle: 1.9,
    orbitSpeed: 0.085,
    selfRotationSpeed: 0.15,
    texture: "/textures/earth.jpg",
    roughness: 0.50,
    metalness: 0.01,
    bumpScale: 0.02,
    hasAtmosphere: true,
    atmosphereColor: "#38bdf8",
  },
  {
    id: "mars",
    name: "Mars",
    service: "Mobile & Native Applications",
    orbitIndex: 3, // Radius 4.8
    size: 0.26,
    initialAngle: 4.8,
    orbitSpeed: 0.065,
    selfRotationSpeed: 0.10,
    texture: "/textures/mars.jpg",
    roughness: 0.75,
    metalness: 0.02,
    bumpScale: 0.03,
    hasAtmosphere: true,
    atmosphereColor: "#f87171",
  },
  {
    id: "jupiter",
    name: "Jupiter",
    service: "Web Applications & SaaS Platforms",
    orbitIndex: 4, // Radius 6.5
    size: 0.52,
    initialAngle: 2.7,
    orbitSpeed: 0.042,
    selfRotationSpeed: 0.14,
    texture: "/textures/jupiter.jpg",
    roughness: 0.90,
    metalness: 0.00,
    bumpScale: 0.01,
    hasAtmosphere: true,
    atmosphereColor: "#fbbf24",
  },
  {
    id: "saturn",
    name: "Saturn",
    service: "ERP & Enterprise Business Systems",
    orbitIndex: 5, // Radius 8.0
    size: 0.44,
    initialAngle: 5.6,
    orbitSpeed: 0.030,
    selfRotationSpeed: 0.08,
    texture: "/textures/saturn.jpg",
    ringTexture: "/textures/saturn_ring.png",
    hasRings: true,
    ringInnerRatio: 1.3,
    ringOuterRatio: 2.6,
    roughness: 0.90,
    metalness: 0.00,
    bumpScale: 0.01,
    hasAtmosphere: true,
    atmosphereColor: "#fef08a",
  },
  {
    id: "uranus",
    name: "Uranus",
    service: "Cloud Architecture & Infrastructure",
    orbitIndex: 6, // Radius 9.4
    size: 0.35,
    initialAngle: 0.4,
    orbitSpeed: 0.022,
    selfRotationSpeed: 0.07,
    texture: "/textures/uranus.jpg",
    roughness: 0.85,
    metalness: 0.00,
    bumpScale: 0.01,
    hasAtmosphere: true,
    atmosphereColor: "#67e8f9",
  },
  {
    id: "neptune",
    name: "Neptune",
    service: "Full-Stack Software Architecture",
    orbitIndex: 7, // Radius 10.8
    size: 0.35,
    initialAngle: 3.9,
    orbitSpeed: 0.016,
    selfRotationSpeed: 0.07,
    texture: "/textures/neptune.jpg",
    roughness: 0.85,
    metalness: 0.00,
    bumpScale: 0.01,
    hasAtmosphere: true,
    atmosphereColor: "#60a5fa",
  },
];
