export const SOLUTIONS_LIST = [
  {
    id: "01",
    title: "CRM Solutions",
    flowTag: "People → Customers",
    description: "Bring customer data, sales activity and relationships into one connected system.",
    supportingConcepts: [
      "Lead management",
      "Customer records",
      "Sales pipelines",
      "Follow-ups",
      "Reporting",
    ],
    nodeType: "crm",
    href: "/solutions/crm",
  },
  {
    id: "02",
    title: "ERP Solutions",
    flowTag: "Operations → Control",
    description: "Connect the workflows, operations and data that keep your business moving.",
    supportingConcepts: [
      "Operations",
      "Inventory",
      "Purchasing",
      "Sales",
      "Finance",
      "Reporting",
    ],
    nodeType: "erp",
    href: "/solutions/erp",
  },
  {
    id: "03",
    title: "Business Automation",
    flowTag: "Process → Automation",
    description: "Replace repetitive manual processes with connected workflows built around your business.",
    supportingConcepts: [
      "Workflow automation",
      "Notifications",
      "Approvals",
      "Data synchronization",
      "System integrations",
    ],
    nodeType: "automation",
    href: "/solutions/business-automation",
  },
  {
    id: "04",
    title: "Ecommerce Solutions",
    flowTag: "Products → Commerce",
    description: "Create commerce experiences that connect products, customers, orders and operations.",
    supportingConcepts: [
      "Product management",
      "Ecommerce storefronts",
      "Orders",
      "Customer experience",
      "Integrations",
    ],
    nodeType: "ecommerce",
    href: "/solutions/ecommerce",
  },
  {
    id: "05",
    title: "Marketing Automation",
    flowTag: "Audience → Growth",
    description: "Connect campaigns, customer journeys and marketing data so growth becomes easier to manage.",
    supportingConcepts: [
      "Campaign workflows",
      "Email automation",
      "Lead nurturing",
      "Customer journeys",
      "Reporting",
    ],
    nodeType: "marketing",
    href: "/solutions/marketing-automation",
  },
];
